# Generated by Django 5.0.7 on 2024-08-26 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(default=None, max_length=50, unique=True)),
                ('adderss1', models.CharField(default=None, max_length=400, verbose_name='Address')),
                ('adderss2', models.CharField(default=None, max_length=400, verbose_name='Address')),
                ('phone', models.CharField(default=None, max_length=11, validators=[django.core.validators.MinLengthValidator(11, 'The Field Must be contain 11 Numbers')])),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=255)),
                ('countery', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
