# Generated by Django 5.0.7 on 2024-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shippingaddress_building_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='building_name',
            field=models.CharField(default=None, max_length=400, null=True, verbose_name='Buliding Name'),
        ),
    ]
