# Generated by Django 5.0.7 on 2024-09-07 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_shippingaddress_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
