# Generated by Django 5.0.7 on 2024-09-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_shippingaddress_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='token',
        ),
    ]
