# Generated by Django 5.0.7 on 2024-09-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_alter_shippingaddress_shipping_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='building_name',
            field=models.CharField(default=None, max_length=400, null=True, verbose_name='Building Name'),
        ),
    ]
