# Generated by Django 5.0.7 on 2024-09-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_alter_shippingaddress_building_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uuid',
            new_name='order_uuid',
        ),
    ]
