# Generated by Django 5.0.7 on 2024-10-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_order_date_shipped'),
    ]

    operations = [
     
    ]
