# Generated by Django 5.0.7 on 2024-07-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_customer_image'),
    ]

    operations = [
        
        
    ]
