# Generated by Django 5.0.7 on 2024-07-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_customer_joined_alter_customer_email_and_more'),
    ]

    operations = [
     
    ]
