# Generated by Django 5.0.7 on 2024-07-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_customer_email'),
    ]

    operations = [
       
    ]
