# Generated by Django 5.0.7 on 2024-07-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_customer_joined'),
    ]

    operations = [
   
    ]
