# Generated by Django 5.0.7 on 2024-07-30 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_customer_created'),
    ]

    operations = [
        
    ]
