# Generated by Django 5.0.7 on 2024-07-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_customer_created'),
    ]

    operations = [
        
    ]
