# Generated by Django 5.0.7 on 2024-07-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_customer_email_alter_customer_first_name'),
    ]

    operations = [
        
    ]
