# Generated by Django 5.0.7 on 2024-08-15 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_customer_password'),
    ]

    operations = [
        
        
    ]
