# Generated by Django 5.0.7 on 2024-08-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_customer_adderss_alter_customer_first_name_and_more'),
    ]

    operations = [
        
    ]
