# Generated by Django 5.0.7 on 2024-08-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_customer_adderss'),
    ]

    operations = [
      
    ]
