# Generated by Django 5.0.7 on 2024-08-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        
    ]
