# Generated by Django 5.0.7 on 2024-08-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
