# Generated by Django 5.0.7 on 2024-08-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_alter_profile_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adderss1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='adderss2',
            new_name='address2',
        ),
    ]
