# Generated by Django 5.0.7 on 2024-08-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_rename_adderss1_profile_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='countery',
            new_name='country',
        ),
    ]
