# Generated by Django 5.0.7 on 2024-09-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_rename_countery_profile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address2',
        ),
    ]
