# Generated by Django 5.0.7 on 2024-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_rename_address1_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
