# Generated by Django 5.0.7 on 2024-07-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('store', '0004_remove_customer_password_customer_user'),
    ]

    operations = [
        
    ]
