# Generated by Django 5.0.7 on 2024-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_foure',
            field=models.ImageField(blank=True, null=True, upload_to='images/products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_three',
            field=models.ImageField(default=1, upload_to='images/products_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(default=1, upload_to='images/products_images'),
            preserve_default=False,
        ),
    ]
