# Generated by Django 5.0.7 on 2024-08-08 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_description'),
    ]

    operations = [
      
    ]
