# Generated by Django 5.0.7 on 2024-08-08 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_product_model'),
    ]

    operations = [
        
    ]
