# Generated by Django 5.0.7 on 2024-08-08 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_name_alter_product_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(20, 'the field must contain at least 20 character')]),
        ),
    ]
