# Generated by Django 5.0.7 on 2024-08-08 06:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_product_model'),
    ]

    operations = [
       
    ]
