# Generated by Django 5.0.7 on 2024-08-08 06:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_product_name_product_product_name_and_more'),
    ]

    operations = [
       
    ]
