# Generated by Django 5.0.7 on 2024-08-08 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_rename_product_name_product_name'),
    ]

    operations = [
        
    ]
