# Generated by Django 5.0.7 on 2024-08-09 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=500, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 20 character')], verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_foure',
            field=models.ImageField(blank=True, null=True, upload_to='images/products_images/related_images', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/products_images/related_images', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/products_images/related_images', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 20 character')], verbose_name='Product Brand'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
