# Generated by Django 5.0.7 on 2024-08-15 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_category_name_alter_product_image_foure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=800, null=True, validators=[django.core.validators.MinLengthValidator(50, 'the field must contain at least 50 characters')]),
        ),
    ]
