# Generated by Django 5.0.7 on 2024-09-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_remove_order_customer_order_user_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
