# Generated by Django 5.0.7 on 2024-09-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_remove_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
