# Generated by Django 5.0.7 on 2024-10-04 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_product_product_uuid'),
    ]

    operations = [
      
    ]
