# Generated by Django 5.0.7 on 2024-10-04 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_remove_product_product_uuid_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1500, null=True, validators=[django.core.validators.MinLengthValidator(50, 'the field must contain at least 50 characters')]),
        ),
    ]
