# Generated by Django 5.0.7 on 2024-10-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_alter_product_fav_products'),
    ]

    operations = [
        
    ]
