# Generated by Django 5.0.7 on 2024-10-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_product_favourites_products'),
    ]

    operations = [
        
    ]
