# Generated by Django 5.0.7 on 2024-11-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_product_instock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
