# Generated by Django 5.0.7 on 2024-11-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
